[Settings]
ID = "uppy"

[main]
# (no main build settings, we use Github Pages)

[context.deploy-preview]
command = "yarn run build && yarn run web:inject-disc && yarn run web:build"
environment = { NODE_VERSION = "16" }
publish = "website/public"
