[Settings]
ID = "uppy"

[main]
# (no main build settings, we use Github Pages)

[context.deploy-preview]
# netlify caches node_modules and doesn't run `npm install` after the first time,
# so we have to `run bootstrap` manually in order to get lerna to do its thing
command = "npm run bootstrap && npm run build && npm run web:install && npm run web:inject-disc && npm run web:build"
publish = "website/public"
