name: CDN
on:
  push:
    branches: main

jobs:
  release:
    if: ${{startsWith(github.event.head_commit.message, 'Release')}}
    name: Publish releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cache npm dependencies
        id: cache-npm-libraries
        uses: actions/cache@v2
        with:
          path: .yarn/cache/*
          key: ${{ runner.os }}
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: corepack yarn install
      - name: Build bundles
        run: corepack yarn run build
      - name: Upload `uppy` to CDN
        run: corepack yarn run uploadcdn uppy
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/robodog` to CDN
        run: corepack yarn run uploadcdn @uppy/robodog
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/locales` to CDN
        run: corepack yarn run uploadcdn @uppy/locales
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
