name: Companion
on: [push, pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.1, 12.x, 14.x, 16.x]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cache npm dependencies
        id: cache-npm-libraries
        uses: actions/cache@v2
        with:
          path: .yarn/cache/*
          key: ${{ runner.os }}
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Corepack if needed
        run: corepack -v || npm install -g corepack
      - name: Install dependencies
        run: corepack yarn install --immutable
        env:
          # Necessary for Node.js v10.x
          NODE_OPTIONS: --experimental-worker
          YARN_IGNORE_NODE: 1
      - name: Run tests
        run: corepack yarn run test:companion
        env:
          # Necessary for Node.js v10.x
          NODE_OPTIONS: --experimental-worker
          YARN_IGNORE_NODE: 1
