name: Release
on:
  pull_request_review:
    types: [submitted]

jobs:
  release:
    name: Publish releases
    if: ${{ github.event.review.state == 'approved' && github.event.sender.login == github.event.pull_request.assignee.login && github.event.pull_request.head.ref == 'release-candidate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Cache npm dependencies
        id: cache-npm-libraries
        uses: actions/cache@v2
        with:
          path: .yarn/cache/*
          key: ${{ runner.os }}
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: corepack yarn install
      - name: Get CHANGELOG diff
        run: git --no-pager diff HEAD^ -- CHANGELOG.md | awk '{ if( substr($0,0,1) == "+" && $1 != "+##" && $1 != "+Released:" && $1 != "+++" ) { print substr($0,2) } }' > CHANGELOG.diff.md
      - name: Build before publishing
        run: corepack yarn run build
      - name: Login to NPM
        run: corepack yarn config set npmAuthToken ${{ toJSON(secrets.NPM_TOKEN) }}
      - name: Publish to NPM
        run: corepack yarn workspaces foreach --no-private npm publish --access public --tolerate-republish
      - name: Merge PR
        id: merge
        run: |
          gh api -X PUT repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
            -F merge_method="squash" \
            -F commit_message="$(cat CHANGELOG.diff.md)" \
            --jq 'if .merged then "##[set-output name=sha;]"+.sha else error("not merged") end'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tags
        run: |
          git --no-pager diff --name-only HEAD^ | awk '$0 ~ /^packages\/.+\/package\.json$/ { print "jq -r '"'"'\"gh api /repos/{owner}/{repo}/git/refs -f ref=\\\"refs/tags/\"+.name+\"@\"+.version+\"\\\" -f sha=${{ steps.merge.outputs.sha }}\"'"'"' < " $0 }' > createTags.sh
          cat createTags.sh
          sh createTags.sh | sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Uppy version number
        id: uppyVersion
        run: jq -r '"##[set-output name=version;]"+.version' < packages/uppy/package.json
      - name: Create GitHub release
        run: gh release create uppy@${{ steps.uppyVersion.outputs.version }} -t "Uppy ${{ steps.uppyVersion.outputs.version }}" -F CHANGELOG.diff.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload `uppy` to CDN
        run: corepack yarn run uploadcdn uppy
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/robodog` to CDN if it was released
        run: git diff --exit-code --quiet HEAD^ -- packages/@uppy/robodog/package.json || corepack yarn run uploadcdn @uppy/robodog
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/locales` to CDN if it was released
        if: false
        run: git diff --exit-code --quiet HEAD^ -- packages/@uppy/locales/package.json ||corepack yarn run uploadcdn @uppy/locales
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Remove release-candidate branch
        run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/release-candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove release branch
        run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Disable Release workflow
        run: gh workflow disable Release --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: In case of failure
        if: ${{ failure() }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "Release job failed, please take action."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
