name: Deploy uppy.io

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(corepack yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: corepack yarn install --immutable
      - name: Build Uppy
        run: corepack yarn run build
      - name: Build website
        run: corepack yarn run web:build
      - name: Prepare deployment
        run: corepack yarn run web:prepare-deploy --quiet
        env:
          DEPLOY_DIR: ${{github.workspace}}/_deploy
      - name: Push to Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _deploy # relative to `github.workspace`
          committer: 'Uppy Bot <uppybot@uppy.io>'
          author: 'Uppy Bot <uppybot@uppy.io>'
          commit_message: Update transloadit/uppy website
          fqdn: uppy.io
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
